# Generated by Django 4.2.13 on 2025-08-21 05:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de Habilidad',
                'verbose_name_plural': 'Categorías de Habilidades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('licencia_conduccion', models.CharField(blank=True, max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('descripcion_corta', models.TextField(max_length=300)),
                ('biografia', models.TextField()),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.TextField(help_text='Tecnologías utilizadas, separadas por comas')),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('mantenimiento', 'En Mantenimiento'), ('pausado', 'Pausado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('url_demo', models.URLField(blank=True)),
                ('url_codigo', models.URLField(blank=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('destacado', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='portfolio.perfil')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-destacado', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=20)),
                ('porcentaje', models.IntegerField(default=0, help_text='Porcentaje de dominio (0-100)')),
                ('descripcion', models.TextField(blank=True)),
                ('años_experiencia', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='portfolio.categoriahabilidad')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='portfolio.perfil')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', '-porcentaje'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('trabajo', 'Trabajo'), ('proyecto', 'Proyecto'), ('freelance', 'Freelance'), ('voluntariado', 'Voluntariado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actual', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('tecnologias', models.TextField(help_text='Tecnologías utilizadas, separadas por comas')),
                ('logros', models.TextField(blank=True, help_text='Logros principales del proyecto/trabajo')),
                ('url_proyecto', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='experiencia/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='portfolio.perfil')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('pregrado', 'Pregrado'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('curso', 'Curso'), ('certificacion', 'Certificación')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('en_curso', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='portfolio.perfil')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('organizacion', models.CharField(max_length=200)),
                ('fecha_obtencion', models.DateField()),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('url_verificacion', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificaciones/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='portfolio.perfil')),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['-fecha_obtencion'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Sitio Web Personal'), ('otro', 'Otro')], max_length=20)),
                ('url', models.URLField()),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='portfolio.perfil')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'unique_together': {('perfil', 'plataforma')},
            },
        ),
    ]
